- README.md
Hey Sebastian,
I am trying to setup the Zurich and Paris scenario. I follow the Readme file to get the baseline result and have found 2 possible typos.
> I have find some possible typo in the readme file

- .gitignore
- CHANGELOG.md
Added iml and idea to gitignore.
> updated gitignore to include iml and idea extensions

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/scenario/cutter/outside/OutsideActivityAdapter.java
- core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/NetworkTripProcessor.java
- core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/DefaultNetworkCrossingPointFinder.java
- core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/NetworkCrossingPointFinder.java
- core/src/main/java/org/eqasim/core/scenario/validation/ScenarioValidator.java
- core/src/main/java/org/eqasim/core/tools/RunIsolateAgent.java
- core/src/test/java/org/eqasim/scenario/cutter/population/trips/TestNetworkTripProcessor.java
> Consider special cases in network route cutting.

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutter.java
- core/src/main/java/org/eqasim/core/scenario/cutter/network/NetworkCutter.java
- core/src/main/java/org/eqasim/core/scenario/cutter/transit/TransitScheduleCutter.java
> Improve public transport cutting

- CHANGELOG.md
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/SanFranciscoModeChoiceModule.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/constraints/VehicleTourConstraintWithCarPassenger.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/constraints/WalkDurationConstraint.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/parameters/SanFranciscoCostParameters.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/parameters/SanFranciscoModeParameters.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/utilities/estimators/SanFranciscoCarUtilityEstimator.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/utilities/estimators/SanFranciscoPTUtilityEstimator.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/utilities/estimators/SanFranciscoWalkUtilityEstimator.java
- san_francisco/src/main/java/org/eqasim/san_francisco/scenario/RunAdaptConfig.java
corrected utility functions, VOTs, added constraints to SF
> Correct utility function

- CHANGELOG.md
- los_angeles/src/main/java/org/eqasim/los_angeles/mode_choice/LosAngelesModeChoiceModule.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/SanFranciscoModeChoiceModule.java
cost instead of mode parameters file is now read for cost values
> fixing files that are read for cost parameters

- sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/parameters/SaoPauloModeParameters.java
- sao_paulo/src/main/java/org/eqasim/sao_paulo/preparation/ExtractResidentialRoadsCoordinates.java
> Fix sao paulo bug

- san_francisco/src/main/java/org/eqasim/san_francisco/RunSimulation.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/SanFranciscoModeAvailability.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/SanFranciscoModeChoiceModule.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/parameters/SanFranciscoModeParameters.java
- san_francisco/src/main/java/org/eqasim/san_francisco/mode_choice/utilities/estimators/SanFranciscoBikeUtilityEstimator.java
adding teleported bike mode to SF
> Add bike sf

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/analysis/RunTripAnalysis.java
- core/src/main/java/org/eqasim/core/analysis/TripReaderFromPopulation.java
> Consider facility / link coordinates in plan-based trip analysis

- .github/workflows/maven.yml
- CHANGELOG.md
- README.md
- docs/versioning.md
- ile_de_france/pom.xml
- pom.xml
- Fix errors related to shade plugin
- Move unit tests from Travis to Github Actions
- Update packaging to packagecloud
> Repository maintenance

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/simulation/mode_choice/epsilon/AbstractEpsilonProvider.java
- core/src/main/java/org/eqasim/core/simulation/mode_choice/epsilon/EpsilonAdapter.java
- core/src/main/java/org/eqasim/core/simulation/mode_choice/epsilon/EpsilonProvider.java
- core/src/main/java/org/eqasim/core/simulation/mode_choice/epsilon/GumbelEpsilonProvider.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/mode_choice/epsilon/EpsilonModule.java
This PR moves the fixed epsilon functionality from
[Hörl, S. (2020) Integrating discrete choice models with MATSim scoring, Procedia Computer Science, 184, 704-711.](https://www.sciencedirect.com/science/article/pii/S1877050921007262?via%3Dihub)
to the main repsoitory.
> Fixed epsilon functionality

- examples/src/main/java/org/eqasim/examples/corsica_vdf/RunCorsicaVDFSimulation.java
Fixing error in CDF example, thx @tkchouaki
> Fix VDF example

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/scenario/cutter/ScenarioWriter.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/IDFConfigurator.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/RunSimulation.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/emissions/EmissionsByPolluant.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/emissions/EmissionsOnLinkEventsHandler.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/emissions/OsmHbefaMapping.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/emissions/RunComputeEmissionsEvents.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/emissions/RunComputeEmissionsGrid.java
- ile_de_france/src/main/java/org/eqasim/ile_de_france/emissions/RunExportEmissionsNetwork.java
- pom.xml
- assign vehicles to agents in RunSimulation
- copy vehicles.xml in the scenario cutter
- compute the emissions event file
- export a regular grid of polutants concentration per hour in a json file
- export the actual polutant emissions per link in a shapefile
> add emissions computation and analysis

- pom.xml
> Bump of jackson dependency

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/tools/routing/BatchPublicTransportRouter.java
- core/src/main/java/org/eqasim/core/tools/routing/BatchRoadRouter.java
- core/src/main/java/org/eqasim/core/tools/routing/RunBatchPublicTransportRouter.java
- core/src/main/java/org/eqasim/core/tools/routing/RunBatchRoadRouter.java
- Allows to set specific utilities for transit routing (waiting, transfers, ...)
- Allows to set time utility for transit modes individually (rail, subway, bus, ...)
> feat: Improve batch routing tools

- ile_de_france/src/main/java/org/eqasim/ile_de_france/RunModeChoice.java
This script isolates the mode choice model and performs it on a whole population. It prints out a plans.xml file as well as a csv file indicating trip modes.
> Isolated mode choice

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/scenario/routing/PlanRouter.java
> fix: Handle only-walk trips in initial routing

- core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java
- core/src/main/java/org/eqasim/core/simulation/mode_choice/utilities/predictors/PtPredictor.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/AbstractAccessDepartureEventCreator.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/TransitWithAbstractAbstractAccessModuleConfigGroup.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/TransitWithAbstractAccessModule.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/TransitWithAbstractAccessQSimModule.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/abstract_access/AbstractAccessItem.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/abstract_access/AbstractAccesses.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/abstract_access/AbstractAccessesFileReader.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/abstract_access/AbstractAccessesFileWriter.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/analysis/AbstractAccessAnalysisOutputListener.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/analysis/AbstractAccessLegItem.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/analysis/AbstractAccessLegListener.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/analysis/AbstractAccessLegWriter.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/events/AbstractAccessDepartureEvent.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/events/AbstractAccessDepartureEventHandler.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/mode_choice/TransitWithAbstractAccessModeAvailabilityWrapper.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/mode_choice/TransitWithAbstractAccessModeChoiceModule.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/mode_choice/constraints/TransitWithAbstractAccessConstraint.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/mode_choice/utilities/estimators/TransitWithAbstractAccessUtilityEstimator.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/mode_choice/utilities/predictors/TransitWithAbstractAccessPredictor.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/routing/AbstractAccessRoute.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/routing/AbstractAccessRouteFactory.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/routing/DefaultAbstractAccessRoute.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/routing/TransitWithAbstractAccessRoutingModule.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/utils/AdaptConfigForTransitWithAbstractAccess.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/utils/CreateAbstractAccessItemsForTransitLines.java
- core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/utils/ExportAbstractAccessItemsToShapefile.java
- core/src/test/java/org/eqasim/TestSimulationPipeline.java
This PR proposes a merging of the functionality presented by the TransitWithAbstractAccessModule in the develop branch so that it keeps being tested with further developments in Eqasim.
As this module is used only by our team currently, no documentation is written yet. This can be done in the future when a large dissemination becomes interesting.
> Feat: Transit with abstract access

- core/src/main/java/org/eqasim/core/tools/ExportLinkTraversals.java
added a script that allows to extract the traversal times (enter and leave) for car trips within a configurable perimeter
> feat: script to export link traversals

- core/src/main/java/org/eqasim/core/simulation/modes/drt/analysis/passengers/PassengerAnalysisListener.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/analysis/passengers/PassengerAnalysisWriter.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/analysis/passengers/PassengerRideItem.java
This small PR just adds a `main_mode` column in the eqasim_drt_passenger_rides.csv generated by the `DrtAnalysisModule`.
> feat: main mode entry in PassengerRideItem

- core/src/main/java/org/eqasim/core/simulation/vdf/VDFConfigGroup.java
- core/src/main/java/org/eqasim/core/simulation/vdf/VDFModule.java
- core/src/main/java/org/eqasim/core/simulation/vdf/VDFUpdateListener.java
- core/src/main/java/org/eqasim/core/simulation/vdf/travel_time/VDFTravelTime.java
This PR allows to restrict the update of the VDF travel times to a an area determined by a Shapefile using a parameter in the config.
> feat: ability to restrict VDF updates to a shapefile area

- core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/CreateDrtVehicles.java
This allows to create drt vehicles only at links that allow at least one of the modes specified in the command line.
> feat: network-modes argument supported in CreateDrtVehicles

- CHANGELOG.md
- switzerland/src/main/java/org/eqasim/switzerland/scenario/RunAdaptConfig.java
- switzerland/src/main/java/org/eqasim/switzerland/scenario/SwissConfigAdapter.java
added parametrization of capacities when downsampling
added freight as subpopulation and corresponding replanning rates
> adaptation of the swiss config

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/scenario/cutter/extent/ShapeScenarioExtent.java
This change adds the possibility to use GeoPackage files to cut scenarios, networks, ...
> feat: define scenario extent in gpkg for cutting

- CHANGELOG.md
- core/src/main/java/org/eqasim/core/analysis/activities/ActivityItem.java
- core/src/main/java/org/eqasim/core/analysis/activities/ActivityListener.java
- core/src/main/java/org/eqasim/core/analysis/activities/ActivityReaderFromEvents.java
- core/src/main/java/org/eqasim/core/analysis/activities/ActivityReaderFromPopulation.java
- core/src/main/java/org/eqasim/core/analysis/activities/ActivityWriter.java
- core/src/main/java/org/eqasim/core/analysis/run/RunActivityAnalysis.java
- core/src/main/java/org/eqasim/core/simulation/analysis/AnalysisOutputListener.java
- core/src/main/java/org/eqasim/core/simulation/analysis/EqasimAnalysisModule.java
This PR adds `eqasim_activities.csv` analogous to the trip analysis that is comparable to the synthetic population input.
> feat: add activity analysis

- core/src/main/java/org/eqasim/core/simulation/mode_choice/EqasimModeChoiceModule.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/mode_choice/constraints/DrtServiceAreaConstraint.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/AdaptConfigForDrt.java
This constraint allows to not consider DRT services for trips where one end is outside of the DRT service area.
> feat: DrtServiceAreaConstraint

- core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java
> chore: EqasimTerminationModule is now optional

- ile_de_france/src/main/java/org/eqasim/ile_de_france/scenario/RunAdaptConfig.java
- los_angeles/src/main/java/org/eqasim/los_angeles/scenario/RunAdaptConfig.java
- san_francisco/src/main/java/org/eqasim/san_francisco/scenario/RunAdaptConfig.java
- sao_paulo/src/main/java/org/eqasim/sao_paulo/scenario/RunAdaptConfig.java
- switzerland/src/main/java/org/eqasim/switzerland/scenario/RunAdaptConfig.java
Fixes a bug identified by @diallitoz when using the latest version of this repository in the IDF pipeline.
> fix: RunAdaptConfig

- core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/analysis/passengers/FeederTripSequenceWriter.java
Small edit that should fix #316
> fix: access/egress StopId columns in FeederTripSequenceWriter

- switzerland/src/main/java/org/eqasim/switzerland/scenario/RunAdaptConfig.java
- switzerland/src/main/java/org/eqasim/switzerland/scenario/SwissConfigAdapter.java
Adjusting swiss config to add vehicles
> feat: Adding vehicles to swiss config

- switzerland/src/main/java/org/eqasim/switzerland/ch/RunVDFSimulation.java
we want to be able to add vdf config group directly in the config file
some minor quality of life changes
> feat: update swiss vdf 

- core/src/main/java/org/eqasim/core/components/traffic/EqasimTrafficQSimModule.java
- core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutterV2.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/mode_choice/constraints/DrtServiceAreaConstraint.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/mode_choice/predictors/DefaultDrtPredictor.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/AdaptConfigForDrt.java
- core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/CreateDrtVehicles.java
- core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/FeederDrtModeModule.java
- core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/router/access_egress_stop_search/AccessEgressStopSearchModule.java
- examples/src/main/java/org/eqasim/examples/corsica_drt/RunCorsicaDrtSimulation.java
- pom.xml
> chore: update matsim to 2026.0-2025w18

- core/src/main/java/org/eqasim/core/tools/sampling/RunDownsampling.java
- core/src/main/java/org/eqasim/core/tools/sampling/ScenarioSampler.java
- core/src/test/java/org/eqasim/TestSimulationPipeline.java
- Creates a suffixed version of the config and the population next to the original version
- Optionally also filters households, vehicles, facilities according to the dropped persons
> feat: downsampling utilities
