eqasim-org/eqasim-java

CHANGELOG.md, core/src/main/java/org/eqasim/core/analysis/DefaultPersonAnalysisFilter.java, core/src/main/java/org/eqasim/core/analysis/pt/PublicTransportTripListener.java, core/src/main/java/org/eqasim/core/components/config/EqasimConfigGroup.java, core/src/main/java/org/eqasim/core/components/transit/EqasimTransitEngine.java, core/src/main/java/org/eqasim/core/components/transit/EqasimTransitQSimModule.java, core/src/main/java/org/eqasim/core/components/transit/routing/DefaultEnrichedTransitRoute.java, core/src/main/java/org/eqasim/core/components/transit/routing/DefaultEnrichedTransitRouter.java, core/src/main/java/org/eqasim/core/components/transit/routing/EnrichedTransitRoute.java, core/src/main/java/org/eqasim/core/components/transit/routing/EnrichedTransitRoutingModule.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/transit/DefaultTransitRouteCrossingPointFinder.java, core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java, core/src/test/java/org/eqasim/scenario/cutter/population/trips/crossing/TestDefaultTransitRouteCrossingPointFinder.java, core/src/test/java/org/eqasim/simulation/transit/routing/TestDefaultEnrichedTransitRoute.java, examples/src/main/java/org/eqasim/examples/zurich_av/RunSimulation.java, ile_de_france/src/main/java/org/eqasim/ile_de_france/mode_choice/costs/IDFPtCostModel.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/RunSimulation.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/costs/SaoPauloPtCostModel.java
- Enables use of simulated public transport in MATSim (detailed vehicle <-> passenger interactions)
- Can be activated by setting `eqasim.useScheduleBasedTransport` to `false` in the configuration
- Fixes #45
=> Simulated public transport vehicles

sao_paulo/src/main/java/org/eqasim/sao_paulo/RunSimulation.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/estimators/SaoPauloCarUtilityEstimator.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/estimators/SaoPauloPTUtilityEstimator.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/estimators/SaoPauloTaxiUtilityEstimator.java
in RunSimulation we now change half of car trips to walk to have a slow approach to equilibrium as previously it was causing a lot of congestion that was not going away
Income elasticity was also removed
=> Test fix congestion

CHANGELOG.md, examples/pom.xml, examples/src/main/java/org/eqasim/examples/corsica_vdf/RunCorsicaVDFSimulation.java, examples/src/test/java/org/eqasim/examples/corsica_vdf/CorsicaVDFSimulationTest.java, pom.xml, vdf/pom.xml, vdf/src/main/java/org/eqasim/vdf/VDFConfigGroup.java, vdf/src/main/java/org/eqasim/vdf/VDFLinkSpeedCalculator.java, vdf/src/main/java/org/eqasim/vdf/VDFModule.java, vdf/src/main/java/org/eqasim/vdf/VDFQSimModule.java, vdf/src/main/java/org/eqasim/vdf/VDFTrafficHandler.java, vdf/src/main/java/org/eqasim/vdf/VDFTravelTime.java, vdf/src/main/java/org/eqasim/vdf/function/BPRFunction.java, vdf/src/main/java/org/eqasim/vdf/function/VolumeDelayFunction.java
To enable traffic simulation based on volume-delay functions:
- Add `VDFConfigGroup` for configuration options, including the definition of time slices in which flows are estimated, and the parameters of the a standard BPR function.
- Add `VDFModule` to enable VDF-based network simulation (travel times will be used in routing via `TravelTime` and in QSim via `LinkSpeedCalculator` based on the average flow over the `horizon` last iterations)
=> Add functionality for volume-delay functions

CHANGELOG.md, core/src/main/java/org/eqasim/core/components/travel_time/RecordedTravelTime.java, core/src/main/java/org/eqasim/core/scenario/cutter/CutterTravelTimeModule.java, core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutter.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/PlanCutter.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/PopulationCutter.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/PopulationCutterModule.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/ModeAwareTripProcessor.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/NetworkTripProcessor.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/TeleportationTripProcessor.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/TransitTripProcessor.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/TripProcessor.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/DefaultNetworkCrossingPointFinder.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/NetworkCrossingPointFinder.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/timing/LinkTimingData.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/timing/LinkTimingRegistry.java, core/src/main/java/org/eqasim/core/scenario/cutter/population/trips/crossing/network/timing/LinkTimingRegistryHandler.java, core/src/test/java/org/eqasim/scenario/cutter/population/trips/TestNetworkTripProcessor.java, core/src/test/java/org/eqasim/scenario/cutter/population/trips/crossing/TestDefaultNetworkCrossingPointFinder.java, pom.xml
This PR makes it possible to optionally process events from a previous simulation during the cutting process. The event information is used for two aspects:
1. Routing of trips through the network is performed based on recorded travel times. Travel time bins are defined based on the `travelTimeCalculator` group in the configuration file
2. Crossing points for network-based modes are obtained from the `LinkEnter`/`LinkLeave` events of the vehicles, i.e. delays along the plans will be considered in with this approach
=> Use event information in cutting process

CHANGELOG.md, ile_de_france/src/main/java/org/eqasim/ile_de_france/scenario/RunAdaptConfig.java
Before, waiting time was not considered in routing as described in #65. Changing this for Ile-de-France for the time being to not mess up other scenarios.
=> Change routing parameter for waiting time to -1 for Ile-de-France

core/src/main/java/org/eqasim/core/scenario/preparation/FacilityPlacement.java, core/src/main/java/org/eqasim/core/scenario/preparation/RunPreparation.java, core/src/main/java/org/eqasim/core/simulation/mode_choice/ParameterDefinition.java
Fixes #131: Car access will be dependent on OSM attributes but can also customized differently. 
Should be unit tested before merging!
=> feat: Control car departure access

core/src/main/java/org/eqasim/core/tools/ExportActivitiesToShapeFile.java, core/src/main/java/org/eqasim/core/tools/ExportActivitiesToShapefile.java, core/src/main/java/org/eqasim/core/tools/ExportPopulationToCSV.java, core/src/main/java/org/eqasim/core/tools/ExportTransitLinesToShapefile.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java
This PR proposes two new tools in the org.eqasim.core.tools package:
- **ExportActivitiesToShapefile**: takes as input a plans file and writes a shapefile with point corresponding to persons' activities with the following information: personId, activity index, activity type, link id, facility id, start time and end time.
- **ExportPopulationToCSV**: also takes a plans file as input. Generates a CSV file containing the persons and their attributes. The attributes are retrieved dynamically from the population, so the header of the file will depend on it. The only column present by default is person_id.
Moreover, the **ExportTransitLinesToShapefile** tool has been extended to allow the selection of transit routes to export (by line id, route id or mode) and also to have the line name written …
=> Two new tools and extending an existing one

CHANGELOG.md, sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/predictors/SaoPauloTaxiPredictor.java
As suggested in https://github.com/eqasim-org/eqasim-java/issues/191#issuecomment-1950041727, I followed the code on https://github.com/eqasim-org/eqasim-java/blob/a8a73b53dbfc085e6eabddcd8ba43fd72013b063/core/src/main/java/org/eqasim/core/simulation/mode_choice/utilities/predictors/CarPredictor.java#L36-L45 to update the code of SaoPauloTaxiPredictor class.
=> add multi-stage taxi trip to SaoPauloTaxiPredictor

core/src/main/java/org/eqasim/core/scenario/routing/RunPopulationRouting.java, core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java, ile_de_france/pom.xml, ile_de_france/src/main/java/org/eqasim/ile_de_france/RunSimulation.java, los_angeles/src/main/java/org/eqasim/los_angeles/RunSimulation.java, san_francisco/src/main/java/org/eqasim/san_francisco/RunSimulation.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/RunSimulation.java, switzerland/src/main/java/org/eqasim/switzerland/RunSimulation.java
* feat:  Optional EqasimTermination module
* fix: making sure no EqasimTerminationModule is instantiated during RunPopulationRouting
* fix: ModeShareModule is part of the Eqasim Termination
* feat: optional config groups added in all run scripts
* fix: imageio requiring vendor name and version in some settings
=> fix: optional eqasim termination (#204)

core/src/main/java/org/eqasim/core/simulation/modes/drt/mode_choice/DrtModeAvailabilityWrapper.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/mode_choice/FeederDrtModeAvailabilityWrapper.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java
The DrtModeAvailabilityWrapper and FeederDrtModeAvailaibilityWrapper offer the functionality of detecting DRT and Feeder DRT modes in the config and adding them as available modes for users, to quickly deploy these modes on the basis of an existing ModeAvailability. 
However the first implementation was not compatible with config files that do not contain these modes, always requiring a mutliModeDrt and a multiModeFeederDrt to work. This PR fixes this by allowing these wrappers to handle null values for the config groups. 
The FeederDrtModeAvailaibilityWrapper is now used in the test instead of explictly passing a list of extra modes to the runMelunSimulation method.
=> DrtModeAvailabilityWrapper and FeederDrtModeAvailabilityWrapper are now compatible with non-drt simulations

core/src/main/java/org/eqasim/core/components/emissions/RunComputeEmissionsEvents.java, core/src/main/java/org/eqasim/core/components/emissions/RunComputeEmissionsGrid.java, core/src/main/java/org/eqasim/core/components/emissions/RunExportEmissionsNetwork.java, core/src/test/java/org/eqasim/TestEmissions.java
Apparently, it is difficult to access the resources of another package once it is actually packaged in a JAR (meaning in the `package` / `verify` / `deploy` phase of Maven, rather than in the `test` phase). So it was not possible anymore to deploy all packages. This PR moves the emissions tests to `core` so it can access the test files for Melun.
=> fix: move emission tests to core

core/src/main/java/org/eqasim/core/components/raptor/EqasimRaptorConfigGroup.java, core/src/main/java/org/eqasim/core/components/raptor/EqasimRaptorModule.java, core/src/main/java/org/eqasim/core/components/raptor/EqasimRaptorUtils.java, core/src/main/java/org/eqasim/core/scenario/config/GenerateConfig.java, core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java, core/src/test/java/org/eqasim/mode_choice/TestSpecialModeChoiceCases.java, ile_de_france/src/main/java/org/eqasim/ile_de_france/scenario/RunAdaptConfig.java
- A recent matsim-libs PR makes it possible to look up costs when routing via the SwissRailRaptor based on the `transportMode` of the respective `TransitRoute`
- In our experimental branches we previously added a similar functionality (routing costs by transport mode) using other hacks
- This PR now integrates the new functionality so we can use it easily without overrides in our code
- The PR introduces the `eqasim:raptor` config module which contains the utility parameters for the most important modes
- The new functionality is activated by default. Currently, the config values are set such that the simulations produce exactly the same results as before. Note that the values may seem a bit odd (-6 and -7), which is due to the "utility of performing and activity" that was previously …
=> feat: separate transit routing costs

core/src/main/java/org/eqasim/core/analysis/pt/PublicTransportLegReaderFromPopulation.java
This PR fixes a broken leg counter in `org.eqasim.core.analysis.pt.PublicTransportLegReaderFromPopulation` used to directly read pt legs from a population to then write them into an eqasim_pt.csv. This is used in the standalone mode choice.
=> fix: broken leg index counter in 

CHANGELOG.md, switzerland/src/main/java/org/eqasim/switzerland/RunSimulation.java
We now have a configurable parameter that allows vehicles to enter the buffer without waiting for enough flow capacity. THis prevents extremely long waiting times of vehicles after cutting scenarios.
=> Swiss code cutout

core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/CreateDrtVehicles.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java
This small PR allows to the `CreateDrtVehicles` script to support a `--service-area-path` to randomly distribute the positions of DRT vehicles only inside a service area.
=> feat: allowing to create vehicles only in service area

core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/mode_choice/utilities/estimator/DefaultFeederDrtUtilityEstimator.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/router/FeederDrtRoutingModule.java
In the previous version Feeder Drt functionality proposed in PR #206, the `FeederDrtRoutingModule`  was putting attributes in feeder interaction activities to signal whether the previous segment of the trip result from the main router (PT) or the access egress one (DRT). This allows to easily separate them as is done in the `DefaultFeederDrtUtilityEstimator`. However, when trying to run a simulation with an input plans resulting from a previous one (with such attributes written in the plans file), the reader throws an exception as attributes in stage activities are not allowed. 
To fix this, the current PR writes the attributes in the legs of the trip segments rather than in the interaction activities.
=> fix: FeederDrt routing attributes in legs rather than in interaction activities

core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/FeederDrtModeModule.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/router/FeederDrtRoutingModule.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/router/access_egress_selector/ClosestAccessEgressStopSelector.java
With this PR, the Feeder Drt module now takes into account the presence of DRT service areas. The `ClosestAccessEgressStopSelector` only considers the access and egress stops inside the service area. Moreover the `FeederDrtRoutingModule` will not use DRT for access (resp. egress) if the from facility (resp. to facility) is located outside the service area.
=> feat: Feeder DRT automatically detects DRT service areas and considers them during routing

core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java, core/src/main/java/org/eqasim/core/simulation/mode_choice/constraints/leg_time/LegTimeConstraint.java, core/src/main/java/org/eqasim/core/simulation/mode_choice/constraints/leg_time/LegTimeConstraintConfigGroup.java, core/src/main/java/org/eqasim/core/simulation/mode_choice/constraints/leg_time/LegTimeConstraintModule.java, core/src/main/java/org/eqasim/core/simulation/mode_choice/constraints/leg_time/LegTimeConstraintSingleLegConfigGroup.java, core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/AdaptConfigForDrt.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/utils/AdaptConfigForFeederDrt.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java
This development started with the need of supporting service times for DRT at the mode choice level. Since the DRT router doesn't check against the vehicles' service time, DRT routes are computed and then the related requests are rejected during Mobsim. A TripConstraint was then implemented to ensure that DRT trip alternatives are considered only in hardcoded time slots. This first version has been developed further to become more generic and not DRT specific and converged to the code base presented in this PR.
The main functionality is made available by the `org.eqasim.core.simulation.mode_choice.constraints.leg_time` package for which the `LegTimeConstraintModule` class is the entry point. The latter is an `AbstractEqasimExtension` that installs the `LegTimeConstraint` in the mode …
=> Leg time constraint

core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutter.java, core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutterV2.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java
The existing `RunScenarioCutter` allows to focus on one small area of a large simulation by considering only the agents that travel in that area at some point during the simulation. The road network, the transit schedule as well as the plans of the concerned agents are 'cut' inside this area. `outside` activities are inserted in the agent plans when they enter or leave the area, and the whole activity sub-chains that take place outside are replaced with trips using the mode `outside`.  This functionality allows, for instance, to study DRT systems on a small scale and perform fleet sizing simulations that take much less time than simulations of the whole area. 
However, one limitiation of the  the current functionalitty is the restriction introduced on the mode choice. To keep plans that …
=> feat: a new scenario cutter without mode choice limitations

core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/utils/AdaptConfigForTransitWithAbstractAccess.java
This step was missing in the `AdaptConfigForTransitWithAbstractAccess` script.
=> fix: adding new mode to DMC cached modes

.github/workflows/maven.yml, core/src/main/java/org/eqasim/core/components/emissions/RunComputeEmissionsGrid.java, core/src/main/java/org/eqasim/core/components/emissions/RunExportEmissionsNetwork.java, core/src/main/java/org/eqasim/core/scenario/RunInsertVehicles.java, core/src/main/java/org/eqasim/core/scenario/SpatialUtils.java, core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutter.java, core/src/main/java/org/eqasim/core/scenario/cutter/extent/ShapeScenarioExtent.java, core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/AdaptConfigForDrt.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/config/AccessEgressStopSelectorParams.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/config/FeederDrtConfigGroup.java, core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/utils/ExportAbstractAccessItemsToShapefile.java, core/src/main/java/org/eqasim/core/tools/ExportActivitiesToShapefile.java, core/src/main/java/org/eqasim/core/tools/ExportNetworkRoutesToGeopackage.java, core/src/main/java/org/eqasim/core/tools/ExportNetworkToGeopackage.java, core/src/main/java/org/eqasim/core/tools/ExportNetworkToShapefile.java, core/src/main/java/org/eqasim/core/tools/ExportTransitLinesToShapefile.java, core/src/main/java/org/eqasim/core/tools/ExportTransitStopsToShapefile.java, core/src/test/java/org/eqasim/TestEmissions.java, core/src/test/java/org/eqasim/mode_choice/TestSpecialModeChoiceCases.java, examples/src/main/java/org/eqasim/examples/corsica_drt/RunCorsicaDrtSimulation.java, los_angeles/src/main/java/org/eqasim/los_angeles/preparation/LATract.java, pom.xml, san_francisco/src/main/java/org/eqasim/san_francisco/preparation/SFTract.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/preparation/SPTract.java
This PR updates eqasim-java to use a more recent version of MATSim. 
A big change here is the update of the java version used in the MATSim repo (now 21) as well as the versions of geotools and commons-io that are used in MATSim. All of these are applied now in Eqasim.
Then, with the new feature implemented in the discrete_mode_choice contrib allowing to write, as an output, the utilities computed by the DMC model, the DiscreteModeChoiceModule now adds a handler that requires an OutputDirectoryHierarchy object. In The scenario cutter, since we do not have such an object, we make sure to filter the modules of the configurator and avoid adding a DiscreteModeChoiceModule.
=> chore: update MATSim version

core/src/test/java/org/eqasim/TestSimulationPipeline.java
Forgot to include a couple of lines in #258
=> chore: [FeederDrt] properly testing TransitStopByIdAccessEgressStopSearch

core/src/main/java/org/eqasim/core/scenario/cutter/RunScenarioCutterV2.java
This PR fixes something I missed to consider in the RunScenarioCutterV2 implementation. The --plans-path argument was taken into account when delegating to the RunScenarioCutter but not when filtering the base population.
=> fix: properly considering the --plans-path argument

core/src/main/java/org/eqasim/core/standalone_mode_choice/RunStandaloneModeChoice.java, core/src/main/java/org/eqasim/core/standalone_mode_choice/StandaloneModeChoiceConfigurator.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java, docs/standalone_mode_choice.md
This PR allows the `RunStandaloneModeChoice` script to use VDF travel times previously recorded in vdf.bin file. One just needs to provide a config file with the `eqasim:vdf` module configured (its `inputFile` parameter should point to the file you want to use)
=> RunStandaloneModeChoice can now use travel times recorded by VDF

core/src/main/java/org/eqasim/core/components/config/ConfigAdapter.java, core/src/main/java/org/eqasim/core/scenario/routing/RunPopulationRouting.java, core/src/main/java/org/eqasim/core/simulation/termination/EqasimTerminationModule.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java, ile_de_france/src/main/java/org/eqasim/ile_de_france/scenario/RunAdaptConfig.java, los_angeles/src/main/java/org/eqasim/los_angeles/scenario/RunAdaptConfig.java, san_francisco/src/main/java/org/eqasim/san_francisco/scenario/RunAdaptConfig.java, sao_paulo/src/main/java/org/eqasim/sao_paulo/scenario/RunAdaptConfig.java
- Need to pass an `EqasimConfigurator` now to `RunAdaptConfig`
- Added `RunPopulationRouting` to the unit tests
- Fixes several problems with handling configuration changes in the scenario pipeline
=> chore: modify RunAdaptConfig behavior

core/src/main/java/org/eqasim/core/components/traffic/DefaultEqasimLinkSpeedCalculator.java, core/src/main/java/org/eqasim/core/components/traffic/EqasimLinkSpeedCalculator.java, core/src/main/java/org/eqasim/core/components/traffic/EqasimTrafficQSimModule.java, core/src/main/java/org/eqasim/core/simulation/vdf/VDFQSimModule.java, core/src/main/java/org/eqasim/core/simulation/vdf/travel_time/VDFLinkSpeedCalculator.java, core/src/test/java/org/eqasim/TestEmissions.java, ile_de_france/src/test/java/org/eqasim/ile_de_france/TestCorisica.java
This PR adapts the code to the new way of configuring the `LinkSpeedCalculator`. In particular, only VDF was using the crossing penalty in recent `develop` versions. Now, also the non-VDF simulations will use the proper calculator that takes into account the crossing penalty.
=> fix: adapt to new way of configuring link speed calculator

core/src/main/java/org/eqasim/core/simulation/vdf/VDFModule.java, core/src/main/java/org/eqasim/core/simulation/vdf/VDFUpdateListener.java, core/src/main/java/org/eqasim/core/simulation/vdf/handlers/VDFHorizonHandler.java, core/src/main/java/org/eqasim/core/simulation/vdf/handlers/VDFInterpolationHandler.java, core/src/main/java/org/eqasim/core/simulation/vdf/handlers/VDFTrafficHandler.java
Various fixes for VDF:
- Ignore flows of the first iteration when a simulation is restarted (because the "iteration 0" that is going to be replayed right in the beginning is supposed to produce the same results as the last flows that are saved in the previous simulation's output flow)
- Add parameter to VDFHandler.aggregate to ignore flows, which also helps in loading the VDF flows and then updating travel times for simple routign applications
- Some fixes in the logic and IO of the interpolation-based handler
=> fix: various fixes for vdf

core/src/main/java/org/eqasim/core/analysis/pt/PublicTransportLegItem.java, core/src/main/java/org/eqasim/core/analysis/pt/PublicTransportLegListener.java, core/src/main/java/org/eqasim/core/analysis/pt/PublicTransportLegReaderFromPopulation.java, core/src/main/java/org/eqasim/core/analysis/pt/PublicTransportLegWriter.java, core/src/main/java/org/eqasim/core/components/transit/EqasimTransitEngine.java, core/src/main/java/org/eqasim/core/components/transit/events/PublicTransitEvent.java, core/src/main/java/org/eqasim/core/components/transit/events/PublicTransitEventMapper.java
This PR adds a departureId attribute in the PublicTransitEvent objects to track the departure used during the simulation (the departure is determined during mobsim and not as part of the transit route).  This allows to have a departureId column in the generated `eqasim_pt.csv` files.
**Note**
Since the departure ID information is not part of the route, it is not stored in the population file, so running the analyses from a plans file without and events file will generate an empty `departure_id` column.
=> feat: departureId in PublicTransitEvent and in eqasim_pt.csv

core/src/main/java/org/eqasim/core/scenario/RunInsertVehicles.java, core/src/test/java/org/eqasim/TestSimulationPipeline.java, pom.xml
This PR just adds some testing in the core module to ensure running the same simulation twice produces the same plans. The test do not cover the output events, but we noticed that two events file from a same simulation differ only in the order in which some events are written in some steps.
To ensure that the tests pass here, the MATSim version is updated to a PR that fixes a determinism issue with SwissRailRaptor.
=> chore: ensuring simulations are deterministic in tests

core/src/main/java/org/eqasim/core/components/travel_time/RecordedTravelTime.java, core/src/main/java/org/eqasim/core/simulation/vdf/handlers/VDFHorizonHandler.java, core/src/main/java/org/eqasim/core/simulation/vdf/handlers/VDFInterpolationHandler.java, core/src/main/java/org/eqasim/core/simulation/vdf/handlers/VDFSparseHorizonHandler.java, core/src/main/java/org/eqasim/core/standalone_mode_choice/RunStandaloneModeChoice.java
In a few places, especially VDF, we were using non-buffered streams which can often be too slow. This PR replaces them by Buffered ones, by going through MATSim's IOUtils.
=> chore: using more efficient buffered streams

core/src/main/java/org/eqasim/core/scenario/config/EditConfig.java, core/src/main/java/org/eqasim/core/simulation/EqasimConfigurator.java
This PR proposes the `org.eqasim.core.scenario.config.EditConfig` script that allows allows to edit a MATSim configuration file exclusively through the command line. 
While existing modules can be configured in most simulation running scripts using the `config:` prefix, existing modules cannot be removed and non-existing ones cannot be added. This is what this script allows to do. 
The script can be used with the following command line arguments: 
- `input-path`: required 
- `output-path`: required
- optional arguments in the form `add-module:moduleName` add the given module to the config. Module config groups matching the provided names are searched in the core modules and the optional modules specified by an EqasimConfigurator 
- optional arguments in the form `remove-module:moduleName` …
=> feat: EditConfig script

core/src/main/java/org/eqasim/core/tools/ExportStopTraversals.java
This PR adds an analysis script that output all stop-to-stop traversals in a simulation. This way, we can analyse (1) passenger volumes between two stops, (2) the number of agents that pass through a pair of stops along their route.
=> feat: analyse stop-to-stop traversals

server/src/main/java/org/eqasim/server/services/router/transit/TransitRouterResponse.java
`in_vehicle_travel_time` -> `in_vehicle_travel_time_min`
=> fix(server): missing suffix in server output

server/src/main/java/org/eqasim/server/RunServer.java
Adds the `--port-path` option to `RunServer` which makes the server write out the port on which it is listening. This is useful if you start the server without the `port` argument or with `--port 0`. This makes the system choose a random open port, which will then be written into your provided port path.
=> feat(server): optionally provide path to write the listening port

.github/workflows/release-please.yml
Fixes compatibility between dependabot and release-please (hopefully), because dependabot PRs don't have access to our specific deployment token.
=> chore: compatibility between release-please and dependabot

core/src/main/java/org/eqasim/core/scenario/routing/PopulationRouter.java
When turn restrictions are turned on, multi-threaded routing concurrently modifies the network. We solve this by creating routers sequentially.
=> feat: fix routing with turn restrictions

core/src/main/java/org/eqasim/core/simulation/modes/drt/utils/AdaptConfigForDrt.java, core/src/main/java/org/eqasim/core/simulation/modes/feeder_drt/utils/AdaptConfigForFeederDrt.java, core/src/main/java/org/eqasim/core/simulation/modes/transit_with_abstract_access/utils/AdaptConfigForTransitWithAbstractAccess.java
This PR makes the configuration scripts for DRT, feeder, and abstract transit also add the respective modes to the termination config group.
=> feat: add additional modes to termination modes
